/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AccountStatus - The status of the account.
 */
public enum AccountStatus {
    ENABLED("Enabled"),
    DISABLED("Disabled"),
    DELETED("Deleted");

    @JsonValue
    public final String value;

    private AccountStatus(String value) {
        this.value = value;
    }
}
