/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AccountDetailsDomesticInternationalResponseInternational - International information of the account
 */

public class AccountDetailsDomesticInternationalResponseInternational {
    /**
     * Account number
     */
    @JsonProperty("account_number")
    public String accountNumber;

    public AccountDetailsDomesticInternationalResponseInternational withAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }
    
    /**
     * Type of Account number
     */
    @JsonProperty("account_number_type")
    public String accountNumberType;

    public AccountDetailsDomesticInternationalResponseInternational withAccountNumberType(String accountNumberType) {
        this.accountNumberType = accountNumberType;
        return this;
    }
    
    /**
     * Bank identifier
     */
    @JsonProperty("bank_identifier")
    public String bankIdentifier;

    public AccountDetailsDomesticInternationalResponseInternational withBankIdentifier(String bankIdentifier) {
        this.bankIdentifier = bankIdentifier;
        return this;
    }
    
    /**
     * Type of bank identifier
     */
    @JsonProperty("bank_identifier_type")
    public String bankIdentifierType;

    public AccountDetailsDomesticInternationalResponseInternational withBankIdentifierType(String bankIdentifierType) {
        this.bankIdentifierType = bankIdentifierType;
        return this;
    }
    
    public AccountDetailsDomesticInternationalResponseInternational(@JsonProperty("account_number") String accountNumber, @JsonProperty("account_number_type") String accountNumberType, @JsonProperty("bank_identifier") String bankIdentifier, @JsonProperty("bank_identifier_type") String bankIdentifierType) {
        this.accountNumber = accountNumber;
        this.accountNumberType = accountNumberType;
        this.bankIdentifier = bankIdentifier;
        this.bankIdentifierType = bankIdentifierType;
  }
}
