/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AccountData - Returns the requested account
 */

public class AccountData {
    /**
     * The list of `AccountDetail`s for this `currency`
     */
    @JsonProperty("account_details")
    public AccountDetails[] accountDetails;

    public AccountData withAccountDetails(AccountDetails[] accountDetails) {
        this.accountDetails = accountDetails;
        return this;
    }
    
    /**
     * The UUID of the account
     */
    @JsonProperty("account_id")
    public String accountId;

    public AccountData withAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The sub-type of the account.
     */
    @JsonProperty("account_subtype")
    public AccountSubType accountSubtype;

    public AccountData withAccountSubtype(AccountSubType accountSubtype) {
        this.accountSubtype = accountSubtype;
        return this;
    }
    
    /**
     * The type of the account.
     */
    @JsonProperty("account_type")
    public AccountType accountType;

    public AccountData withAccountType(AccountType accountType) {
        this.accountType = accountType;
        return this;
    }
    
    /**
     * Identification of the currency in which the account is held
     */
    @JsonProperty("currency")
    public String currency;

    public AccountData withCurrency(String currency) {
        this.currency = currency;
        return this;
    }
    
    /**
     * The status of the account.
     */
    @JsonProperty("status")
    public AccountStatus status;

    public AccountData withStatus(AccountStatus status) {
        this.status = status;
        return this;
    }
    
    public AccountData(@JsonProperty("account_details") AccountDetails[] accountDetails, @JsonProperty("account_id") String accountId, @JsonProperty("account_subtype") AccountSubType accountSubtype, @JsonProperty("account_type") AccountType accountType, @JsonProperty("currency") String currency, @JsonProperty("status") AccountStatus status) {
        this.accountDetails = accountDetails;
        this.accountId = accountId;
        this.accountSubtype = accountSubtype;
        this.accountType = accountType;
        this.currency = currency;
        this.status = status;
  }
}
