/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AccountType - The type of the account.
 */
public enum AccountType {
    PERSONAL("Personal"),
    BUSINESS("Business");

    @JsonValue
    public final String value;

    private AccountType(String value) {
        this.value = value;
    }
}
