/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class Amount {
    /**
     * The amount of the transaction.
     */
    @JsonProperty("amount")
    public String amount;

    public Amount withAmount(String amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The ISO 4217 code of the transaction currency
     */
    @JsonProperty("currency")
    public String currency;

    public Amount withCurrency(String currency) {
        this.currency = currency;
        return this;
    }
    
    public Amount(@JsonProperty("amount") String amount, @JsonProperty("currency") String currency) {
        this.amount = amount;
        this.currency = currency;
  }
}
