/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class BalanceAmount {
    /**
     * The amount of the balance.
     */
    @JsonProperty("amount")
    public String amount;

    public BalanceAmount withAmount(String amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The ISO 4217 code of the balance currency
     */
    @JsonProperty("currency")
    public String currency;

    public BalanceAmount withCurrency(String currency) {
        this.currency = currency;
        return this;
    }
    
    public BalanceAmount(@JsonProperty("amount") String amount, @JsonProperty("currency") String currency) {
        this.amount = amount;
        this.currency = currency;
  }
}
