/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * BalanceType - This is an enumeration of the balance types of an account.
 */
public enum BalanceType {
    INTERIM_AVAILABLE("InterimAvailable"),
    REQUIRED_FUNDS("RequiredFunds");

    @JsonValue
    public final String value;

    private BalanceType(String value) {
        this.value = value;
    }
}
