/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;

/**
 * Beneficiary - The core data of a beneficiary.
 */

public class Beneficiary {
    /**
     * True if beneficiary is active, False otherwise.
     */
    @JsonProperty("active")
    public Boolean active;

    public Beneficiary withActive(Boolean active) {
        this.active = active;
        return this;
    }
    
    /**
     * The first address line of the beneficiary.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address_line_1")
    public String addressLine1;

    public Beneficiary withAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
        return this;
    }
    
    /**
     * AML status of the beneficiary.
     */
    @JsonProperty("aml_status")
    public BeneficiaryAmlStatus amlStatus;

    public Beneficiary withAmlStatus(BeneficiaryAmlStatus amlStatus) {
        this.amlStatus = amlStatus;
        return this;
    }
    
    /**
     * The list of beneficiary's bank accounts.
     */
    @JsonProperty("bank_accounts")
    public BankAccount[] bankAccounts;

    public Beneficiary withBankAccounts(BankAccount[] bankAccounts) {
        this.bankAccounts = bankAccounts;
        return this;
    }
    
    /**
     * The identifier of the beneficiary.
     */
    @JsonProperty("beneficiary_id")
    public String beneficiaryId;

    public Beneficiary withBeneficiaryId(String beneficiaryId) {
        this.beneficiaryId = beneficiaryId;
        return this;
    }
    
    /**
     * The reference for the beneficiary.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("beneficiary_reference")
    public String beneficiaryReference;

    public Beneficiary withBeneficiaryReference(String beneficiaryReference) {
        this.beneficiaryReference = beneficiaryReference;
        return this;
    }
    
    /**
     * The ISO 3166-1 alpha-2 code of the beneficiary's country.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country_code")
    public String countryCode;

    public Beneficiary withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    /**
     * Creation date of the beneficiary.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("created")
    public LocalDate created;

    public Beneficiary withCreated(LocalDate created) {
        this.created = created;
        return this;
    }
    
    /**
     * The list of beneficiary's email addresses.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email_addresses")
    public String[] emailAddresses;

    public Beneficiary withEmailAddresses(String[] emailAddresses) {
        this.emailAddresses = emailAddresses;
        return this;
    }
    
    /**
     * Whether the beneficiary should receive email notification of payments.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email_notification")
    public Boolean emailNotification;

    public Beneficiary withEmailNotification(Boolean emailNotification) {
        this.emailNotification = emailNotification;
        return this;
    }
    
    /**
     * The name of the beneficiary.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public Beneficiary withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The post code of the beneficiary.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("post_code")
    public String postCode;

    public Beneficiary withPostCode(String postCode) {
        this.postCode = postCode;
        return this;
    }
    
    public Beneficiary(@JsonProperty("active") Boolean active, @JsonProperty("aml_status") BeneficiaryAmlStatus amlStatus, @JsonProperty("bank_accounts") BankAccount[] bankAccounts, @JsonProperty("beneficiary_id") String beneficiaryId, @JsonProperty("created") LocalDate created) {
        this.active = active;
        this.amlStatus = amlStatus;
        this.bankAccounts = bankAccounts;
        this.beneficiaryId = beneficiaryId;
        this.created = created;
  }
}
