/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class BeneficiaryMetadataItemCurrencies {
    /**
     * The currency code, expressed as an ISO 4217 alpha code. The value 'default' means the requirements for any currency not otherwise listed for this country.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currency")
    public String currency;

    public BeneficiaryMetadataItemCurrencies withCurrency(String currency) {
        this.currency = currency;
        return this;
    }
    
    /**
     * The data that must provided to provision a beneficiary for the country and currency, provided in groups i.e. one of the groups must be matched to provision a beneficiary for the country/currency combination.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mandatory_data")
    public String[][] mandatoryData;

    public BeneficiaryMetadataItemCurrencies withMandatoryData(String[][] mandatoryData) {
        this.mandatoryData = mandatoryData;
        return this;
    }
    
    /**
     * Data that can optionally be included to provision a beneficiary. Additional context available where  then a value is included in the definition e.g. bank_identifierSort Code.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("optional_data")
    public String[] optionalData;

    public BeneficiaryMetadataItemCurrencies withOptionalData(String[] optionalData) {
        this.optionalData = optionalData;
        return this;
    }
    
    public BeneficiaryMetadataItemCurrencies(){}
}
