/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ConfirmedTradeBankAccount - An existing bank account
 */

public class ConfirmedTradeBankAccount {
    @JsonProperty("account_number")
    public String accountNumber;

    public ConfirmedTradeBankAccount withAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }
    
    @JsonProperty("bank_address_line_1")
    public String bankAddressLine1;

    public ConfirmedTradeBankAccount withBankAddressLine1(String bankAddressLine1) {
        this.bankAddressLine1 = bankAddressLine1;
        return this;
    }
    
    @JsonProperty("bank_address_line_2")
    public String bankAddressLine2;

    public ConfirmedTradeBankAccount withBankAddressLine2(String bankAddressLine2) {
        this.bankAddressLine2 = bankAddressLine2;
        return this;
    }
    
    @JsonProperty("bank_city")
    public String bankCity;

    public ConfirmedTradeBankAccount withBankCity(String bankCity) {
        this.bankCity = bankCity;
        return this;
    }
    
    @JsonProperty("bank_identifier")
    public String bankIdentifier;

    public ConfirmedTradeBankAccount withBankIdentifier(String bankIdentifier) {
        this.bankIdentifier = bankIdentifier;
        return this;
    }
    
    @JsonProperty("bank_identifier_type")
    public String bankIdentifierType;

    public ConfirmedTradeBankAccount withBankIdentifierType(String bankIdentifierType) {
        this.bankIdentifierType = bankIdentifierType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_name")
    public String bankName;

    public ConfirmedTradeBankAccount withBankName(String bankName) {
        this.bankName = bankName;
        return this;
    }
    
    @JsonProperty("bank_post_code")
    public String bankPostCode;

    public ConfirmedTradeBankAccount withBankPostCode(String bankPostCode) {
        this.bankPostCode = bankPostCode;
        return this;
    }
    
    @JsonProperty("iban")
    public String iban;

    public ConfirmedTradeBankAccount withIban(String iban) {
        this.iban = iban;
        return this;
    }
    
    @JsonProperty("swift_code")
    public String swiftCode;

    public ConfirmedTradeBankAccount withSwiftCode(String swiftCode) {
        this.swiftCode = swiftCode;
        return this;
    }
    
    public ConfirmedTradeBankAccount(@JsonProperty("account_number") String accountNumber, @JsonProperty("bank_address_line_1") String bankAddressLine1, @JsonProperty("bank_address_line_2") String bankAddressLine2, @JsonProperty("bank_city") String bankCity, @JsonProperty("bank_identifier") String bankIdentifier, @JsonProperty("bank_identifier_type") String bankIdentifierType, @JsonProperty("bank_post_code") String bankPostCode, @JsonProperty("iban") String iban, @JsonProperty("swift_code") String swiftCode) {
        this.accountNumber = accountNumber;
        this.bankAddressLine1 = bankAddressLine1;
        this.bankAddressLine2 = bankAddressLine2;
        this.bankCity = bankCity;
        this.bankIdentifier = bankIdentifier;
        this.bankIdentifierType = bankIdentifierType;
        this.bankPostCode = bankPostCode;
        this.iban = iban;
        this.swiftCode = swiftCode;
  }
}
