/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CurrencyMetadataItem {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("buy")
    public CutOffItem buy;

    public CurrencyMetadataItem withBuy(CutOffItem buy) {
        this.buy = buy;
        return this;
    }
    
    /**
     * The currency code, expressed as an ISO 4217 alpha code.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currency")
    public String currency;

    public CurrencyMetadataItem withCurrency(String currency) {
        this.currency = currency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("invalid_value_dates")
    public InvalidValueDateItem invalidValueDates;

    public CurrencyMetadataItem withInvalidValueDates(InvalidValueDateItem invalidValueDates) {
        this.invalidValueDates = invalidValueDates;
        return this;
    }
    
    /**
     * Whether or not a reason for trade for the currency needs to be supplied.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reason_required")
    public Boolean reasonRequired;

    public CurrencyMetadataItem withReasonRequired(Boolean reasonRequired) {
        this.reasonRequired = reasonRequired;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sell")
    public CutOffItem sell;

    public CurrencyMetadataItem withSell(CutOffItem sell) {
        this.sell = sell;
        return this;
    }
    
    public CurrencyMetadataItem(){}
}
