/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CurrencyInfoCutoff {
    /**
     * Cutoff days for the currency. The value 0 means there is not cutoff day for this currency.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("day")
    public Long day;

    public CurrencyInfoCutoff withDay(Long day) {
        this.day = day;
        return this;
    }
    
    /**
     * Cutoff time for the currency. Includes TZ data in ISO format
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("time")
    public String time;

    public CurrencyInfoCutoff withTime(String time) {
        this.time = time;
        return this;
    }
    
    public CurrencyInfoCutoff(){}
}
