/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CutOffItem {
    /**
     * The cutoff T+n days, expressed as an integer. The value '0' means there is not cutoff day for this currency.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cutoff_days")
    public Long cutoffDays;

    public CutOffItem withCutoffDays(Long cutoffDays) {
        this.cutoffDays = cutoffDays;
        return this;
    }
    
    /**
     * The cutoff time, expressed as an string. The value 'null' means there is not cutoff time for this currency.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cutoff_time")
    public String cutoffTime;

    public CutOffItem withCutoffTime(String cutoffTime) {
        this.cutoffTime = cutoffTime;
        return this;
    }
    
    public CutOffItem(){}
}
