/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EnumMassPaymentStatus - This is an enumeration of the status of a MassPayment
 */
public enum EnumMassPaymentStatus {
    QUEUED_FOR_PROCESSING("Queued for processing"),
    PROCESSING("Processing"),
    PROCESSED("Processed"),
    QUEUED_FOR_CREATING("Queued for creating"),
    CREATING("Creating"),
    CREATED("Created"),
    CANCELLED("Cancelled"),
    FAILED("Failed");

    @JsonValue
    public final String value;

    private EnumMassPaymentStatus(String value) {
        this.value = value;
    }
}
