/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ErrorMessage - An error message.
 */

public class ErrorMessage {
    /**
     * The code for the error.
     */
    @JsonProperty("code")
    public String code;

    public ErrorMessage withCode(String code) {
        this.code = code;
        return this;
    }
    
    /**
     * Error details
     */
    @JsonProperty("details")
    public String details;

    public ErrorMessage withDetails(String details) {
        this.details = details;
        return this;
    }
    
    /**
     * A short description of the cause of the error.
     */
    @JsonProperty("message")
    public String message;

    public ErrorMessage withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public ErrorMessage(@JsonProperty("code") String code, @JsonProperty("details") String details, @JsonProperty("message") String message) {
        this.code = code;
        this.details = details;
        this.message = message;
  }
}
