/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FxAvailability - Get if the FX markets are available at the time or not
 */

public class FxAvailability {
    /**
     * True if FX markets are available at this time, False otherwise.
     */
    @JsonProperty("fx_available")
    public Boolean fxAvailable;

    public FxAvailability withFxAvailable(Boolean fxAvailable) {
        this.fxAvailable = fxAvailable;
        return this;
    }
    
    public FxAvailability(@JsonProperty("fx_available") Boolean fxAvailable) {
        this.fxAvailable = fxAvailable;
  }
}
