/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class InvalidValueDateItem {
    /**
     * Reason of invalid trading date.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("YYYY-MM-DD")
    public String yyyyMmDd;

    public InvalidValueDateItem withYyyyMmDd(String yyyyMmDd) {
        this.yyyyMmDd = yyyyMmDd;
        return this;
    }
    
    public InvalidValueDateItem(){}
}
