/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MassPaymentResponse - Masspayment request accepted, see response body for status
 */

public class MassPaymentResponse {
    /**
     * The external reference for the MassPayment, if supplied
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_reference_id")
    public String externalReferenceId;

    public MassPaymentResponse withExternalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
        return this;
    }
    
    /**
     * The UUID of the MassPayment just created
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mass_payment_id")
    public String massPaymentId;

    public MassPaymentResponse withMassPaymentId(String massPaymentId) {
        this.massPaymentId = massPaymentId;
        return this;
    }
    
    /**
     * This is an enumeration of the status of a MassPayment
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mass_payment_status")
    public EnumMassPaymentStatus massPaymentStatus;

    public MassPaymentResponse withMassPaymentStatus(EnumMassPaymentStatus massPaymentStatus) {
        this.massPaymentStatus = massPaymentStatus;
        return this;
    }
    
    public MassPaymentResponse(){}
}
