/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;


public class MultiPaymentResponseTradeDetails {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("buy_amount")
    public Float buyAmount;

    public MultiPaymentResponseTradeDetails withBuyAmount(Float buyAmount) {
        this.buyAmount = buyAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("buy_currency")
    public String buyCurrency;

    public MultiPaymentResponseTradeDetails withBuyCurrency(String buyCurrency) {
        this.buyCurrency = buyCurrency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_rate")
    public Float clientRate;

    public MultiPaymentResponseTradeDetails withClientRate(Float clientRate) {
        this.clientRate = clientRate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_rate_symbol")
    public String clientRateSymbol;

    public MultiPaymentResponseTradeDetails withClientRateSymbol(String clientRateSymbol) {
        this.clientRateSymbol = clientRateSymbol;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("inverse_rate")
    public Float inverseRate;

    public MultiPaymentResponseTradeDetails withInverseRate(Float inverseRate) {
        this.inverseRate = inverseRate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("inverse_rate_symbol")
    public String inverseRateSymbol;

    public MultiPaymentResponseTradeDetails withInverseRateSymbol(String inverseRateSymbol) {
        this.inverseRateSymbol = inverseRateSymbol;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sell_amount")
    public Float sellAmount;

    public MultiPaymentResponseTradeDetails withSellAmount(Float sellAmount) {
        this.sellAmount = sellAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sell_currency")
    public String sellCurrency;

    public MultiPaymentResponseTradeDetails withSellCurrency(String sellCurrency) {
        this.sellCurrency = sellCurrency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("value_date")
    public LocalDate valueDate;

    public MultiPaymentResponseTradeDetails withValueDate(LocalDate valueDate) {
        this.valueDate = valueDate;
        return this;
    }
    
    public MultiPaymentResponseTradeDetails(){}
}
