/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MultiPaymentResponseAccountDetails - The data of the bank account. Refer to the Metadata API for valid field combinations.
 */

public class MultiPaymentResponseAccountDetails {
    /**
     * The identifier of the bank account.
     */
    @JsonProperty("account_id")
    public Long accountId;

    public MultiPaymentResponseAccountDetails withAccountId(Long accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The account number of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_number")
    public String accountNumber;

    public MultiPaymentResponseAccountDetails withAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }
    
    /**
     * The first address line of the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_address_line_1")
    public String bankAddressLine1;

    public MultiPaymentResponseAccountDetails withBankAddressLine1(String bankAddressLine1) {
        this.bankAddressLine1 = bankAddressLine1;
        return this;
    }
    
    /**
     * The ISO 3166-1 alpha-2 code of the bank's country.
     */
    @JsonProperty("bank_country_code")
    public String bankCountryCode;

    public MultiPaymentResponseAccountDetails withBankCountryCode(String bankCountryCode) {
        this.bankCountryCode = bankCountryCode;
        return this;
    }
    
    /**
     * The ISO 4217 code of the bank account's currency.
     */
    @JsonProperty("bank_currency_code")
    public String bankCurrencyCode;

    public MultiPaymentResponseAccountDetails withBankCurrencyCode(String bankCurrencyCode) {
        this.bankCurrencyCode = bankCurrencyCode;
        return this;
    }
    
    /**
     * The identifier of the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_identifier")
    public String bankIdentifier;

    public MultiPaymentResponseAccountDetails withBankIdentifier(String bankIdentifier) {
        this.bankIdentifier = bankIdentifier;
        return this;
    }
    
    /**
     * Name of the bank account holder.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_name")
    public String bankName;

    public MultiPaymentResponseAccountDetails withBankName(String bankName) {
        this.bankName = bankName;
        return this;
    }
    
    /**
     * The account for the correspondant account of the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("correspondent_account")
    public String correspondentAccount;

    public MultiPaymentResponseAccountDetails withCorrespondentAccount(String correspondentAccount) {
        this.correspondentAccount = correspondentAccount;
        return this;
    }
    
    /**
     * The SWIFT code for the correspondant account of the bank.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("correspondent_swift_code")
    public String correspondentSwiftCode;

    public MultiPaymentResponseAccountDetails withCorrespondentSwiftCode(String correspondentSwiftCode) {
        this.correspondentSwiftCode = correspondentSwiftCode;
        return this;
    }
    
    /**
     * The IBAN of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("iban")
    public String iban;

    public MultiPaymentResponseAccountDetails withIban(String iban) {
        this.iban = iban;
        return this;
    }
    
    /**
     * The INN of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("inn")
    public String inn;

    public MultiPaymentResponseAccountDetails withInn(String inn) {
        this.inn = inn;
        return this;
    }
    
    /**
     * The KBK of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kbk")
    public String kbk;

    public MultiPaymentResponseAccountDetails withKbk(String kbk) {
        this.kbk = kbk;
        return this;
    }
    
    /**
     * The KIO of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kio")
    public String kio;

    public MultiPaymentResponseAccountDetails withKio(String kio) {
        this.kio = kio;
        return this;
    }
    
    /**
     * The KPP of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kpp")
    public String kpp;

    public MultiPaymentResponseAccountDetails withKpp(String kpp) {
        this.kpp = kpp;
        return this;
    }
    
    /**
     * Text explaining the purpose of payment. Required by the Central Bank for all payments sent to China (CHN) in the Chinese Renminbi (CNY) currency or United Arab Emirates in any currency (GDE to RDA) [Coming soon].
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("purpose_of_payment")
    public MultiPaymentResponseAccountDetailsPurposeOfPayment purposeOfPayment;

    public MultiPaymentResponseAccountDetails withPurposeOfPayment(MultiPaymentResponseAccountDetailsPurposeOfPayment purposeOfPayment) {
        this.purposeOfPayment = purposeOfPayment;
        return this;
    }
    
    /**
     * The reason for trade of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reason_for_trade")
    public String reasonForTrade;

    public MultiPaymentResponseAccountDetails withReasonForTrade(String reasonForTrade) {
        this.reasonForTrade = reasonForTrade;
        return this;
    }
    
    /**
     * The reference information of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reference_information")
    public String referenceInformation;

    public MultiPaymentResponseAccountDetails withReferenceInformation(String referenceInformation) {
        this.referenceInformation = referenceInformation;
        return this;
    }
    
    /**
     * The Russian central account number of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("russian_central_bank_account")
    public String russianCentralBankAccount;

    public MultiPaymentResponseAccountDetails withRussianCentralBankAccount(String russianCentralBankAccount) {
        this.russianCentralBankAccount = russianCentralBankAccount;
        return this;
    }
    
    /**
     * The SWIFT code of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("swift_code")
    public String swiftCode;

    public MultiPaymentResponseAccountDetails withSwiftCode(String swiftCode) {
        this.swiftCode = swiftCode;
        return this;
    }
    
    /**
     * The VO of the bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vo")
    public String vo;

    public MultiPaymentResponseAccountDetails withVo(String vo) {
        this.vo = vo;
        return this;
    }
    
    public MultiPaymentResponseAccountDetails(@JsonProperty("account_id") Long accountId, @JsonProperty("bank_country_code") String bankCountryCode, @JsonProperty("bank_currency_code") String bankCurrencyCode) {
        this.accountId = accountId;
        this.bankCountryCode = bankCountryCode;
        this.bankCurrencyCode = bankCurrencyCode;
  }
}
