/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class NewPaymentItem {
    /**
     * Fee amount
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fee_amount")
    public Float feeAmount;

    public NewPaymentItem withFeeAmount(Float feeAmount) {
        this.feeAmount = feeAmount;
        return this;
    }
    
    /**
     * Fee currency
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fee_currency")
    public String feeCurrency;

    public NewPaymentItem withFeeCurrency(String feeCurrency) {
        this.feeCurrency = feeCurrency;
        return this;
    }
    
    /**
     * The payment identifier
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_id")
    public String paymentId;

    public NewPaymentItem withPaymentId(String paymentId) {
        this.paymentId = paymentId;
        return this;
    }
    
    /**
     * URI to download payment instruction
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_instruction")
    public String paymentInstruction;

    public NewPaymentItem withPaymentInstruction(String paymentInstruction) {
        this.paymentInstruction = paymentInstruction;
        return this;
    }
    
    /**
     * URI to download payment receipt
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_receipt")
    public String paymentReceipt;

    public NewPaymentItem withPaymentReceipt(String paymentReceipt) {
        this.paymentReceipt = paymentReceipt;
        return this;
    }
    
    /**
     * Payment reference
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reference")
    public String reference;

    public NewPaymentItem withReference(String reference) {
        this.reference = reference;
        return this;
    }
    
    /**
     * The current status of the payment
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public NewPaymentItemStatus status;

    public NewPaymentItem withStatus(NewPaymentItemStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * A warning is only returned if the requested value date was not valid and the next available date has been returned.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("warning")
    public String warning;

    public NewPaymentItem withWarning(String warning) {
        this.warning = warning;
        return this;
    }
    
    public NewPaymentItem(){}
}
