/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * NewTradeReason - Reason for trade. The 'not_related_to_goods_or_services' reason is only for spot type.
 */
public enum NewTradeReason {
    CHARITABLE_AID("charitable_aid"),
    PAYMENT_FOR_GOODS("payment_for_goods"),
    CAPITAL_INVESTMENT("capital_investment"),
    PAYMENT_FOR_SERVICES("payment_for_services"),
    REPATRIATION_OF_GOODS("repatriation_of_goods"),
    REPATRIATION_OF_SERVICES("repatriation_of_services"),
    PROPERTY_PURCHASE("property_purchase"),
    MORTAGE_REPAYMENT("mortage_repayment"),
    PROPERTY_RENTAL_OR_MAINTENANCE("property_rental_or_maintenance"),
    SALARY_PAYROLL("salary_payroll"),
    TRAVEL_COSTS("travel_costs"),
    LIVING_COSTS("living_costs"),
    REPAYMENT_OF_LOAN("repayment_of_loan"),
    BALANCE_HEDGING("balance_hedging"),
    REPATRIATION_FROM_INVESTMENT("repatriation_from_investment"),
    PORTFOLIO_NETTING("portfolio_netting"),
    NOT_RELATED_TO_GOODS_OR_SERVICES("not_related_to_goods_or_services"),
    OTHER("other");

    @JsonValue
    public final String value;

    private NewTradeReason(String value) {
        this.value = value;
    }
}
