/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PaymentFee - This model is a representation of a payment fee.
 */

public class PaymentFee {
    /**
     * Beneficiary identifier
     */
    @JsonProperty("beneficiary_id")
    public String beneficiaryId;

    public PaymentFee withBeneficiaryId(String beneficiaryId) {
        this.beneficiaryId = beneficiaryId;
        return this;
    }
    
    /**
     * Fee amount
     */
    @JsonProperty("fee_amount")
    public Float feeAmount;

    public PaymentFee withFeeAmount(Float feeAmount) {
        this.feeAmount = feeAmount;
        return this;
    }
    
    /**
     * Fee currency
     */
    @JsonProperty("fee_currency")
    public String feeCurrency;

    public PaymentFee withFeeCurrency(String feeCurrency) {
        this.feeCurrency = feeCurrency;
        return this;
    }
    
    /**
     * Payment amount
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_amount")
    public Float paymentAmount;

    public PaymentFee withPaymentAmount(Float paymentAmount) {
        this.paymentAmount = paymentAmount;
        return this;
    }
    
    /**
     * The destination country of the payment
     */
    @JsonProperty("payment_country")
    public String paymentCountry;

    public PaymentFee withPaymentCountry(String paymentCountry) {
        this.paymentCountry = paymentCountry;
        return this;
    }
    
    /**
     * Currency the payment was made in
     */
    @JsonProperty("payment_currency")
    public String paymentCurrency;

    public PaymentFee withPaymentCurrency(String paymentCurrency) {
        this.paymentCurrency = paymentCurrency;
        return this;
    }
    
    /**
     * True if payment is Ebury intra payments, False otherwise
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_is_intra")
    public Boolean paymentIsIntra;

    public PaymentFee withPaymentIsIntra(Boolean paymentIsIntra) {
        this.paymentIsIntra = paymentIsIntra;
        return this;
    }
    
    public PaymentFee(@JsonProperty("beneficiary_id") String beneficiaryId, @JsonProperty("fee_amount") Float feeAmount, @JsonProperty("fee_currency") String feeCurrency, @JsonProperty("payment_country") String paymentCountry, @JsonProperty("payment_currency") String paymentCurrency) {
        this.beneficiaryId = beneficiaryId;
        this.feeAmount = feeAmount;
        this.feeCurrency = feeCurrency;
        this.paymentCountry = paymentCountry;
        this.paymentCurrency = paymentCurrency;
  }
}
