/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PaymentFeeEstimate - This model is a representation of a payment fee estimate.
 */

public class PaymentFeeEstimate {
    /**
     * Fee amount
     */
    @JsonProperty("fee_amount")
    public Float feeAmount;

    public PaymentFeeEstimate withFeeAmount(Float feeAmount) {
        this.feeAmount = feeAmount;
        return this;
    }
    
    /**
     * Fee currency
     */
    @JsonProperty("fee_currency")
    public String feeCurrency;

    public PaymentFeeEstimate withFeeCurrency(String feeCurrency) {
        this.feeCurrency = feeCurrency;
        return this;
    }
    
    /**
     * Payment amount
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_amount")
    public Float paymentAmount;

    public PaymentFeeEstimate withPaymentAmount(Float paymentAmount) {
        this.paymentAmount = paymentAmount;
        return this;
    }
    
    /**
     * The destination country of the payment
     */
    @JsonProperty("payment_country")
    public String paymentCountry;

    public PaymentFeeEstimate withPaymentCountry(String paymentCountry) {
        this.paymentCountry = paymentCountry;
        return this;
    }
    
    /**
     * Currency the payment was made in
     */
    @JsonProperty("payment_currency")
    public String paymentCurrency;

    public PaymentFeeEstimate withPaymentCurrency(String paymentCurrency) {
        this.paymentCurrency = paymentCurrency;
        return this;
    }
    
    /**
     * payment instruction
     */
    @JsonProperty("payment_instruction")
    public String paymentInstruction;

    public PaymentFeeEstimate withPaymentInstruction(String paymentInstruction) {
        this.paymentInstruction = paymentInstruction;
        return this;
    }
    
    /**
     * True if payment is Ebury intra payments, False otherwise
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_is_intra")
    public Boolean paymentIsIntra;

    public PaymentFeeEstimate withPaymentIsIntra(Boolean paymentIsIntra) {
        this.paymentIsIntra = paymentIsIntra;
        return this;
    }
    
    public PaymentFeeEstimate(@JsonProperty("fee_amount") Float feeAmount, @JsonProperty("fee_currency") String feeCurrency, @JsonProperty("payment_country") String paymentCountry, @JsonProperty("payment_currency") String paymentCurrency, @JsonProperty("payment_instruction") String paymentInstruction) {
        this.feeAmount = feeAmount;
        this.feeCurrency = feeCurrency;
        this.paymentCountry = paymentCountry;
        this.paymentCurrency = paymentCurrency;
        this.paymentInstruction = paymentInstruction;
  }
}
