/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * QuoteRequestOperation - Operation (buy or sell)
 */
public enum QuoteRequestOperation {
    BUY("buy"),
    SELL("sell");

    @JsonValue
    public final String value;

    private QuoteRequestOperation(String value) {
        this.value = value;
    }
}
