/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * StatementFileStatus - Returns the current status of the statement
 */

public class StatementFileStatus {
    /**
     * The status of the statement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public StatementStatus status;

    public StatementFileStatus withStatus(StatementStatus status) {
        this.status = status;
        return this;
    }
    
    public StatementFileStatus(){}
}
