/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TransactionDataTransactionType - Type of the transaction
 */
public enum TransactionDataTransactionType {
    CREDIT("credit"),
    DEBIT("debit"),
    INCOMING("incoming"),
    MARGIN("margin"),
    PAYMENT_RETURNED("payment_returned");

    @JsonValue
    public final String value;

    private TransactionDataTransactionType(String value) {
        this.value = value;
    }
}
