/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type - The document type: pi (payment instruction), pr (payment receipt), tr (trade receipt).
 */
public enum Type {
    PI("pi"),
    PR("pr"),
    TR("tr");

    @JsonValue
    public final String value;

    private Type(String value) {
        this.value = value;
    }
}
