/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class BeneficiariesPostResponse {
    /**
     * Beneficiary created.
     */
    
    public ebury.ebury.models.shared.Beneficiary beneficiary;

    public BeneficiariesPostResponse withBeneficiary(ebury.ebury.models.shared.Beneficiary beneficiary) {
        this.beneficiary = beneficiary;
        return this;
    }
    
    
    public String contentType;

    public BeneficiariesPostResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting, parameter or schema validation error. See error message for further details.
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public BeneficiariesPostResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    
    public Integer statusCode;

    public BeneficiariesPostResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public BeneficiariesPostResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public BeneficiariesPostResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
