/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class BeneficiariesGetRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public BeneficiariesGetRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * Filter. The account number of the beneficiary you want to search.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=account_number")
    public String accountNumber;

    public BeneficiariesGetRequest withAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }
    
    /**
     * Filter. The bank identifier of the account of the beneficiary you want to search.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=bank_identifier")
    public String bankIdentifier;

    public BeneficiariesGetRequest withBankIdentifier(String bankIdentifier) {
        this.bankIdentifier = bankIdentifier;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public BeneficiariesGetRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * Filter. The iban of the account of the beneficiary you want to search.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=iban")
    public String iban;

    public BeneficiariesGetRequest withIban(String iban) {
        this.iban = iban;
        return this;
    }
    
    /**
     * The desired page number for pagination. By default is 1.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Integer page;

    public BeneficiariesGetRequest withPage(Integer page) {
        this.page = page;
        return this;
    }
    
    /**
     * The number of items per page for pagination. By default is 50.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    public Integer pageSize;

    public BeneficiariesGetRequest withPageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }
    
    public BeneficiariesGetRequest(@JsonProperty("client_id") String clientId) {
        this.clientId = clientId;
  }
}
