/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class BeneficiaryGetRequest {
    /**
     * The identifier of a contact.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public BeneficiaryGetRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The identifier of a beneficiary.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=beneficiary_id")
    public String beneficiaryId;

    public BeneficiaryGetRequest withBeneficiaryId(String beneficiaryId) {
        this.beneficiaryId = beneficiaryId;
        return this;
    }
    
    /**
     * The identifier of a client.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public BeneficiaryGetRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    public BeneficiaryGetRequest(@JsonProperty("beneficiary_id") String beneficiaryId, @JsonProperty("client_id") String clientId) {
        this.beneficiaryId = beneficiaryId;
        this.clientId = clientId;
  }
}
