/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class ContactGetRequest {
    /**
     * The identifier of a contact.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public ContactGetRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The identifier of a client.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public ContactGetRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * The identifier of a contact.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contact_id")
    public String contactId;

    public ContactGetRequest withContactId(String contactId) {
        this.contactId = contactId;
        return this;
    }
    
    public ContactGetRequest(@JsonProperty("client_id") String clientId, @JsonProperty("contact_id") String contactId) {
        this.clientId = clientId;
        this.contactId = contactId;
  }
}
