/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetAccountsRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public GetAccountsRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetAccountsRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * A comma-separated list of currencies
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=currencies")
    public String currencies;

    public GetAccountsRequest withCurrencies(String currencies) {
        this.currencies = currencies;
        return this;
    }
    
    public GetAccountsRequest(@JsonProperty("client_id") String clientId, @JsonProperty("currencies") String currencies) {
        this.clientId = clientId;
        this.currencies = currencies;
  }
}
