/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetAccountsAccountIdBalancesRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public GetAccountsAccountIdBalancesRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The UUID of the account
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")
    public String accountId;

    public GetAccountsAccountIdBalancesRequest withAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The balance types to be retrieved
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=balance_types")
    public GetAccountsAccountIdBalancesBalanceTypes balanceTypes;

    public GetAccountsAccountIdBalancesRequest withBalanceTypes(GetAccountsAccountIdBalancesBalanceTypes balanceTypes) {
        this.balanceTypes = balanceTypes;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetAccountsAccountIdBalancesRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    public GetAccountsAccountIdBalancesRequest(@JsonProperty("account_id") String accountId, @JsonProperty("client_id") String clientId) {
        this.accountId = accountId;
        this.clientId = clientId;
  }
}
