/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetAccountsAccountIdTransactionsCreditDebitIndicator - Filter transactions by debit/credit type
 */
public enum GetAccountsAccountIdTransactionsCreditDebitIndicator {
    CREDIT("credit"),
    DEBIT("debit");

    @JsonValue
    public final String value;

    private GetAccountsAccountIdTransactionsCreditDebitIndicator(String value) {
        this.value = value;
    }
}
