/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetAccountsAccountIdStatementsStatementIdFileResponse {
    
    public String contentType;

    public GetAccountsAccountIdStatementsStatementIdFileResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting, parameter or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public GetAccountsAccountIdStatementsStatementIdFileResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    /**
     * Returns the current status of the statement
     */
    
    public ebury.ebury.models.shared.StatementFileStatus statementFileStatus;

    public GetAccountsAccountIdStatementsStatementIdFileResponse withStatementFileStatus(ebury.ebury.models.shared.StatementFileStatus statementFileStatus) {
        this.statementFileStatus = statementFileStatus;
        return this;
    }
    
    
    public Integer statusCode;

    public GetAccountsAccountIdStatementsStatementIdFileResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetAccountsAccountIdStatementsStatementIdFileResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetAccountsAccountIdStatementsStatementIdFileResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
