/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetAuthenticateRequest {
    /**
     * Your Authorization Client ID, identifies your application to the Authorisation Server
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetAuthenticateRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * The redirect URL that is registered for your application. This must match the value we hold.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=redirect_uri")
    public String redirectUri;

    public GetAuthenticateRequest withRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
        return this;
    }
    
    /**
     * The response type required from the Authorization Server. This must be set to code
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=response_type")
    public GetAuthenticateResponseType responseType;

    public GetAuthenticateRequest withResponseType(GetAuthenticateResponseType responseType) {
        this.responseType = responseType;
        return this;
    }
    
    /**
     * The OAuth 2.0 scope parameter. Must include the value openid. No other values required.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scope")
    public String scope;

    public GetAuthenticateRequest withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    /**
     * The OAuth 2.0 state parameter.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=state")
    public String state;

    public GetAuthenticateRequest withState(String state) {
        this.state = state;
        return this;
    }
    
    public GetAuthenticateRequest(@JsonProperty("client_id") String clientId, @JsonProperty("redirect_uri") String redirectUri, @JsonProperty("response_type") GetAuthenticateResponseType responseType, @JsonProperty("scope") String scope, @JsonProperty("state") String state) {
        this.clientId = clientId;
        this.redirectUri = redirectUri;
        this.responseType = responseType;
        this.scope = scope;
        this.state = state;
  }
}
