/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetAuthenticateResponseType - The response type required from the Authorization Server. This must be set to code
 */
public enum GetAuthenticateResponseType {
    CODE("code");

    @JsonValue
    public final String value;

    private GetAuthenticateResponseType(String value) {
        this.value = value;
    }
}
