/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetAccountsAccountIdRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public GetAccountsAccountIdRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * Account UUID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")
    public String accountId;

    public GetAccountsAccountIdRequest withAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetAccountsAccountIdRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    public GetAccountsAccountIdRequest(@JsonProperty("account_id") String accountId, @JsonProperty("client_id") String clientId) {
        this.accountId = accountId;
        this.clientId = clientId;
  }
}
