/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetAccountDetailsAccountDetailsType - Filter by the type of the account details
 */
public enum GetAccountDetailsAccountDetailsType {
    DEDICATED("dedicated"),
    POOLED("pooled");

    @JsonValue
    public final String value;

    private GetAccountDetailsAccountDetailsType(String value) {
        this.value = value;
    }
}
