/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetBalancesBalanceTypes - The balance types to be retrieved
 */
public enum GetBalancesBalanceTypes {
    REQUIRED_FUNDS("RequiredFunds"),
    INTERIM_AVAILABLE("InterimAvailable");

    @JsonValue
    public final String value;

    private GetBalancesBalanceTypes(String value) {
        this.value = value;
    }
}
