/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;




public class GetInfoAvailableContactsRequest {
    public GetInfoAvailableContactsRequest(){}
}
