/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetInfoAvailableContactsResponse {
    /**
     * Formatting or schema validation error or invalid data.See error message for further details.
     */
    
    public ebury.ebury.models.shared.AuthErrorMessage authErrorMessage;

    public GetInfoAvailableContactsResponse withAuthErrorMessage(ebury.ebury.models.shared.AuthErrorMessage authErrorMessage) {
        this.authErrorMessage = authErrorMessage;
        return this;
    }
    
    /**
     * Listf of contacts IDs that are from the given client
     */
    
    public ebury.ebury.models.shared.ContactsList contactsList;

    public GetInfoAvailableContactsResponse withContactsList(ebury.ebury.models.shared.ContactsList contactsList) {
        this.contactsList = contactsList;
        return this;
    }
    
    
    public String contentType;

    public GetInfoAvailableContactsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetInfoAvailableContactsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetInfoAvailableContactsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetInfoAvailableContactsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
