/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetMassPaymentsMassPaymentIdErrorsRequest {
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetMassPaymentsMassPaymentIdErrorsRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * The mass payment ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=mass_payment_id")
    public String massPaymentId;

    public GetMassPaymentsMassPaymentIdErrorsRequest withMassPaymentId(String massPaymentId) {
        this.massPaymentId = massPaymentId;
        return this;
    }
    
    /**
     * The desired page number for pagination. By default is 1.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Integer page;

    public GetMassPaymentsMassPaymentIdErrorsRequest withPage(Integer page) {
        this.page = page;
        return this;
    }
    
    /**
     * The number of items per page for pagination. By default is 50.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    public Integer pageSize;

    public GetMassPaymentsMassPaymentIdErrorsRequest withPageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }
    
    /**
     * Filter by payment currency
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=payment_currency")
    public String paymentCurrency;

    public GetMassPaymentsMassPaymentIdErrorsRequest withPaymentCurrency(String paymentCurrency) {
        this.paymentCurrency = paymentCurrency;
        return this;
    }
    
    public GetMassPaymentsMassPaymentIdErrorsRequest(@JsonProperty("client_id") String clientId, @JsonProperty("mass_payment_id") String massPaymentId) {
        this.clientId = clientId;
        this.massPaymentId = massPaymentId;
  }
}
