/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetMassPaymentsMassPaymentIdErrorsResponse {
    
    public String contentType;

    public GetMassPaymentsMassPaymentIdErrorsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting, parameter or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public GetMassPaymentsMassPaymentIdErrorsResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public GetMassPaymentsMassPaymentIdErrorsResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    /**
     * List of payment instructions with errors
     */
    
    public ebury.ebury.models.shared.PaymentInstructionWithErrors[] massPaymentErrorsResponse;

    public GetMassPaymentsMassPaymentIdErrorsResponse withMassPaymentErrorsResponse(ebury.ebury.models.shared.PaymentInstructionWithErrors[] massPaymentErrorsResponse) {
        this.massPaymentErrorsResponse = massPaymentErrorsResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMassPaymentsMassPaymentIdErrorsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMassPaymentsMassPaymentIdErrorsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetMassPaymentsMassPaymentIdErrorsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
