/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetMetadataCurrencyResponse {
    
    public String contentType;

    public GetMetadataCurrencyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Currency metadata
     */
    
    public ebury.ebury.models.shared.CurrencyMetadataItem[] currencyMetadata;

    public GetMetadataCurrencyResponse withCurrencyMetadata(ebury.ebury.models.shared.CurrencyMetadataItem[] currencyMetadata) {
        this.currencyMetadata = currencyMetadata;
        return this;
    }
    
    /**
     * Formatting, parameter or schema validation error. See error message for further details.
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public GetMetadataCurrencyResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMetadataCurrencyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMetadataCurrencyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetMetadataCurrencyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
