/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetPaymentsFeesRequest {
    /**
     * The ID of the beneficiary
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=beneficiary_id")
    public String beneficiaryId;

    public GetPaymentsFeesRequest withBeneficiaryId(String beneficiaryId) {
        this.beneficiaryId = beneficiaryId;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetPaymentsFeesRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * The amount of the payment
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=payment_amount")
    public Float paymentAmount;

    public GetPaymentsFeesRequest withPaymentAmount(Float paymentAmount) {
        this.paymentAmount = paymentAmount;
        return this;
    }
    
    public GetPaymentsFeesRequest(@JsonProperty("beneficiary_id") String beneficiaryId, @JsonProperty("client_id") String clientId, @JsonProperty("payment_amount") Float paymentAmount) {
        this.beneficiaryId = beneficiaryId;
        this.clientId = clientId;
        this.paymentAmount = paymentAmount;
  }
}
