/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetPaymentsFeesEstimateResponse {
    
    public String contentType;

    public GetPaymentsFeesEstimateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting, parameter or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public GetPaymentsFeesEstimateResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    /**
     * The list of payment estimate fee
     */
    
    public ebury.ebury.models.shared.PaymentFeeEstimate paymentFeeEstimate;

    public GetPaymentsFeesEstimateResponse withPaymentFeeEstimate(ebury.ebury.models.shared.PaymentFeeEstimate paymentFeeEstimate) {
        this.paymentFeeEstimate = paymentFeeEstimate;
        return this;
    }
    
    
    public Integer statusCode;

    public GetPaymentsFeesEstimateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetPaymentsFeesEstimateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetPaymentsFeesEstimateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
