/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetQuotesFxAvailabilityResponse {
    
    public String contentType;

    public GetQuotesFxAvailabilityResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting, parameter or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public GetQuotesFxAvailabilityResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    /**
     * Get if the FX markets are available at the time or not
     */
    
    public ebury.ebury.models.shared.FxAvailability fxAvailability;

    public GetQuotesFxAvailabilityResponse withFxAvailability(ebury.ebury.models.shared.FxAvailability fxAvailability) {
        this.fxAvailability = fxAvailability;
        return this;
    }
    
    
    public Integer statusCode;

    public GetQuotesFxAvailabilityResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetQuotesFxAvailabilityResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetQuotesFxAvailabilityResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
