/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum GetTradesTradeType {
    SPOT("spot"),
    FORWARD("forward"),
    WINDOW_FORWARD("window_forward"),
    DRAWDOWN("drawdown"),
    NDF("ndf");

    @JsonValue
    public final String value;

    private GetTradesTradeType(String value) {
        this.value = value;
    }
}
