/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetTradesTradeIdRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public GetTradesTradeIdRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetTradesTradeIdRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * Trade identifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=trade_id")
    public String tradeId;

    public GetTradesTradeIdRequest withTradeId(String tradeId) {
        this.tradeId = tradeId;
        return this;
    }
    
    public GetTradesTradeIdRequest(@JsonProperty("client_id") String clientId, @JsonProperty("trade_id") String tradeId) {
        this.clientId = clientId;
        this.tradeId = tradeId;
  }
}
