/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class GetTransactionsRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public GetTransactionsRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public GetTransactionsRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * Filter transactions by debit/credit type
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=credit_debit_indicator")
    public GetTransactionsCreditDebitIndicator creditDebitIndicator;

    public GetTransactionsRequest withCreditDebitIndicator(GetTransactionsCreditDebitIndicator creditDebitIndicator) {
        this.creditDebitIndicator = creditDebitIndicator;
        return this;
    }
    
    /**
     * A comma-separated list of currency codes compliant to ISO 4217
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=currencies")
    public String currencies;

    public GetTransactionsRequest withCurrencies(String currencies) {
        this.currencies = currencies;
        return this;
    }
    
    /**
     * Only return transactions with value date and time after this UTC date and time. YYYY-MM-DDThh:mm format
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=from_value_datetime")
    public String fromValueDatetime;

    public GetTransactionsRequest withFromValueDatetime(String fromValueDatetime) {
        this.fromValueDatetime = fromValueDatetime;
        return this;
    }
    
    /**
     * The desired page number for pagination
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;

    public GetTransactionsRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    /**
     * The number of items per page for pagination
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    public Long pageSize;

    public GetTransactionsRequest withPageSize(Long pageSize) {
        this.pageSize = pageSize;
        return this;
    }
    
    /**
     * Only return transactions with value date and time before this UTC date and time. YYYY-MM-DDThh:mm format
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=to_value_datetime")
    public String toValueDatetime;

    public GetTransactionsRequest withToValueDatetime(String toValueDatetime) {
        this.toValueDatetime = toValueDatetime;
        return this;
    }
    
    /**
     * Only return transactions of the specified transaction type.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=transaction_type")
    public ebury.ebury.models.shared.TransactionTypeFilter transactionType;

    public GetTransactionsRequest withTransactionType(ebury.ebury.models.shared.TransactionTypeFilter transactionType) {
        this.transactionType = transactionType;
        return this;
    }
    
    public GetTransactionsRequest(@JsonProperty("client_id") String clientId, @JsonProperty("currencies") String currencies) {
        this.clientId = clientId;
        this.currencies = currencies;
  }
}
