/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class PatchPaymentsPaymentIdRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public PatchPaymentsPaymentIdRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The action to take (authorise or reject)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=action")
    public PatchPaymentsPaymentIdAction action;

    public PatchPaymentsPaymentIdRequest withAction(PatchPaymentsPaymentIdAction action) {
        this.action = action;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public PatchPaymentsPaymentIdRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * Unique idenifier for payment
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=payment_id")
    public String paymentId;

    public PatchPaymentsPaymentIdRequest withPaymentId(String paymentId) {
        this.paymentId = paymentId;
        return this;
    }
    
    public PatchPaymentsPaymentIdRequest(@JsonProperty("action") PatchPaymentsPaymentIdAction action, @JsonProperty("client_id") String clientId, @JsonProperty("payment_id") String paymentId) {
        this.action = action;
        this.clientId = clientId;
        this.paymentId = paymentId;
  }
}
