/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PatchMultipaymentsMultipaymentIdResponse {
    /**
     * Multi payment accepted and payments booked (pending back office operations)
     */
    
    public ebury.ebury.models.shared.BankAccount bankAccount;

    public PatchMultipaymentsMultipaymentIdResponse withBankAccount(ebury.ebury.models.shared.BankAccount bankAccount) {
        this.bankAccount = bankAccount;
        return this;
    }
    
    
    public String contentType;

    public PatchMultipaymentsMultipaymentIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public PatchMultipaymentsMultipaymentIdResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    
    public Integer statusCode;

    public PatchMultipaymentsMultipaymentIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PatchMultipaymentsMultipaymentIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PatchMultipaymentsMultipaymentIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
