/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PatchPaymentsPaymentIdAction - The action to take (authorise or reject)
 */
public enum PatchPaymentsPaymentIdAction {
    AUTHORISE("authorise"),
    REJECT("reject");

    @JsonValue
    public final String value;

    private PatchPaymentsPaymentIdAction(String value) {
        this.value = value;
    }
}
