/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class PatchAccountDetailsAccountDetailsIdRequest {
    /**
     * Payload to patch the referred account details
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ebury.ebury.models.shared.PatchAccountDetailsRequest patchAccountDetailsRequest;

    public PatchAccountDetailsAccountDetailsIdRequest withPatchAccountDetailsRequest(ebury.ebury.models.shared.PatchAccountDetailsRequest patchAccountDetailsRequest) {
        this.patchAccountDetailsRequest = patchAccountDetailsRequest;
        return this;
    }
    
    /**
     * Unique ID of account details
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_details_id")
    public String accountDetailsId;

    public PatchAccountDetailsAccountDetailsIdRequest withAccountDetailsId(String accountDetailsId) {
        this.accountDetailsId = accountDetailsId;
        return this;
    }
    
    /**
     * ID of the client that owns the account
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public PatchAccountDetailsAccountDetailsIdRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    public PatchAccountDetailsAccountDetailsIdRequest(@JsonProperty("PatchAccountDetailsRequest") ebury.ebury.models.shared.PatchAccountDetailsRequest patchAccountDetailsRequest, @JsonProperty("account_details_id") String accountDetailsId, @JsonProperty("client_id") String clientId) {
        this.patchAccountDetailsRequest = patchAccountDetailsRequest;
        this.accountDetailsId = accountDetailsId;
        this.clientId = clientId;
  }
}
