/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PostAuthenticateResponse {
    
    public byte[] body;

    public PostAuthenticateResponse withBody(byte[] body) {
        this.body = body;
        return this;
    }
    
    
    public String contentType;

    public PostAuthenticateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting or schema validation error or invalid data.See error message for further details.
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public PostAuthenticateResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    
    public Integer statusCode;

    public PostAuthenticateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostAuthenticateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * HTML login template
     */
    
    public String postAuthenticate200ApplicationJSONString;

    public PostAuthenticateResponse withPostAuthenticate200ApplicationJSONString(String postAuthenticate200ApplicationJSONString) {
        this.postAuthenticate200ApplicationJSONString = postAuthenticate200ApplicationJSONString;
        return this;
    }
    
    /**
     * HTML login template
     */
    
    public String postAuthenticate200TextHTMLString;

    public PostAuthenticateResponse withPostAuthenticate200TextHTMLString(String postAuthenticate200TextHTMLString) {
        this.postAuthenticate200TextHTMLString = postAuthenticate200TextHTMLString;
        return this;
    }
    
    public PostAuthenticateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
