/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class PostTokenContactIdRequest {
    /**
     * The id of the contact
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contact_id")
    public String contactId;

    public PostTokenContactIdRequest withContactId(String contactId) {
        this.contactId = contactId;
        return this;
    }
    
    public PostTokenContactIdRequest(@JsonProperty("contact_id") String contactId) {
        this.contactId = contactId;
  }
}
