/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class PostAccountsAccountIdStatementsFileRequest {
    /**
     * Request Payload
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ebury.ebury.models.shared.NewStatement newStatement;

    public PostAccountsAccountIdStatementsFileRequest withNewStatement(ebury.ebury.models.shared.NewStatement newStatement) {
        this.newStatement = newStatement;
        return this;
    }
    
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public PostAccountsAccountIdStatementsFileRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * Account UUID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")
    public String accountId;

    public PostAccountsAccountIdStatementsFileRequest withAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public PostAccountsAccountIdStatementsFileRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    /**
     * The format of the statement to generate
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=format")
    public String format;

    public PostAccountsAccountIdStatementsFileRequest withFormat(String format) {
        this.format = format;
        return this;
    }
    
    public PostAccountsAccountIdStatementsFileRequest(@JsonProperty("NewStatement") ebury.ebury.models.shared.NewStatement newStatement, @JsonProperty("account_id") String accountId, @JsonProperty("client_id") String clientId) {
        this.newStatement = newStatement;
        this.accountId = accountId;
        this.clientId = clientId;
  }
}
