/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PostVerifyResponse {
    /**
     * Formatting or schema validation error or invalid data.See error message for further details.
     */
    
    public ebury.ebury.models.shared.AuthErrorMessage authErrorMessage;

    public PostVerifyResponse withAuthErrorMessage(ebury.ebury.models.shared.AuthErrorMessage authErrorMessage) {
        this.authErrorMessage = authErrorMessage;
        return this;
    }
    
    
    public byte[] body;

    public PostVerifyResponse withBody(byte[] body) {
        this.body = body;
        return this;
    }
    
    
    public String contentType;

    public PostVerifyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public PostVerifyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostVerifyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Redirect to your redirect_url
     */
    
    public String postVerify302ApplicationJSONString;

    public PostVerifyResponse withPostVerify302ApplicationJSONString(String postVerify302ApplicationJSONString) {
        this.postVerify302ApplicationJSONString = postVerify302ApplicationJSONString;
        return this;
    }
    
    /**
     * Redirect to your redirect_url
     */
    
    public String postVerify302TextHTMLString;

    public PostVerifyResponse withPostVerify302TextHTMLString(String postVerify302TextHTMLString) {
        this.postVerify302TextHTMLString = postVerify302TextHTMLString;
        return this;
    }
    
    public PostVerifyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
