/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class PostWebhooksGraphqlRequest {
    /**
     * Request Payload
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ebury.ebury.models.shared.WebhooksRequest webhooksRequest;

    public PostWebhooksGraphqlRequest withWebhooksRequest(ebury.ebury.models.shared.WebhooksRequest webhooksRequest) {
        this.webhooksRequest = webhooksRequest;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public PostWebhooksGraphqlRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    public PostWebhooksGraphqlRequest(@JsonProperty("WebhooksRequest") ebury.ebury.models.shared.WebhooksRequest webhooksRequest, @JsonProperty("client_id") String clientId) {
        this.webhooksRequest = webhooksRequest;
        this.clientId = clientId;
  }
}
