/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PostMultipaymentsResponse {
    
    public String contentType;

    public PostMultipaymentsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public PostMultipaymentsResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    /**
     * All payments invalid or partial instruction not allowed, see response body for details
     */
    
    public ebury.ebury.models.shared.MultiPaymentError[] multiPaymentErrorMessage;

    public PostMultipaymentsResponse withMultiPaymentErrorMessage(ebury.ebury.models.shared.MultiPaymentError[] multiPaymentErrorMessage) {
        this.multiPaymentErrorMessage = multiPaymentErrorMessage;
        return this;
    }
    
    /**
     * Multi payment created, see response body for status
     */
    
    public ebury.ebury.models.shared.MultiPaymentResponse multiPaymentResponse;

    public PostMultipaymentsResponse withMultiPaymentResponse(ebury.ebury.models.shared.MultiPaymentResponse multiPaymentResponse) {
        this.multiPaymentResponse = multiPaymentResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public PostMultipaymentsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostMultipaymentsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PostMultipaymentsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
