/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import ebury.ebury.utils.SpeakeasyMetadata;


public class PostMassPaymentsDollarMassPaymentIdConfirmRequest {
    /**
     * The ID of the contact
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Contact-ID")
    public String xContactID;

    public PostMassPaymentsDollarMassPaymentIdConfirmRequest withXContactID(String xContactID) {
        this.xContactID = xContactID;
        return this;
    }
    
    /**
     * The ID of the client
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;

    public PostMassPaymentsDollarMassPaymentIdConfirmRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    public PostMassPaymentsDollarMassPaymentIdConfirmRequest(@JsonProperty("client_id") String clientId) {
        this.clientId = clientId;
  }
}
