/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ebury.ebury.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PostMassPaymentsResponse {
    
    public String contentType;

    public PostMassPaymentsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Formatting or schema validation error. See error message for further details
     */
    
    public ebury.ebury.models.shared.ErrorMessage errorMessage;

    public PostMassPaymentsResponse withErrorMessage(ebury.ebury.models.shared.ErrorMessage errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    /**
     * Masspayment request accepted, see response body for status
     */
    
    public ebury.ebury.models.shared.MassPaymentResponse massPaymentResponse;

    public PostMassPaymentsResponse withMassPaymentResponse(ebury.ebury.models.shared.MassPaymentResponse massPaymentResponse) {
        this.massPaymentResponse = massPaymentResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public PostMassPaymentsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostMassPaymentsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PostMassPaymentsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
